version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: ProductWBsyncBot
    volumes:
      - .:/code
    depends_on:
      - postgres
    command: python main.py
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_HOST: postgres

volumes:
  postgres_data:
